#!/bin/bash

read a op b

if [ "$op" = "+" ]; then
  echo $((a + b))
elif [ "$op" = "-" ]; then
  echo $((a - b))
elif [ "$op" = "*" ]; then
  echo $((a * b))
elif [ "$op" = "/" ]; then
  echo $((a / b))
fi
